
import React from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Customer } from "@/types/customer";

interface CustomerPDFReportProps {
  customer: Customer;
  analytics: any;
  onClose: () => void;
}

const CustomerPDFReport: React.FC<CustomerPDFReportProps> = ({ customer, analytics, onClose }) => {
  const generatePDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Customer Report - ${customer.name}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            .header { text-align: center; border-bottom: 2px solid #22c55e; padding-bottom: 20px; margin-bottom: 30px; }
            .company-name { color: #22c55e; font-size: 24px; font-weight: bold; }
            .customer-info { background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
            .analytics-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }
            .analytics-card { background: #f8f9fa; padding: 15px; border-radius: 8px; text-align: center; }
            .analytics-card h3 { margin: 0 0 10px 0; color: #333; }
            .analytics-card .value { font-size: 24px; font-weight: bold; color: #22c55e; }
            .balance-status { padding: 10px; border-radius: 5px; margin: 10px 0; text-align: center; font-weight: bold; }
            .balance-positive { background: #fee2e2; color: #dc2626; }
            .balance-zero { background: #d1fae5; color: #059669; }
            .balance-negative { background: #dbeafe; color: #2563eb; }
            @media print { body { margin: 0; } }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="company-name">GO GREEN LEAFY VEGETABLES</div>
            <div>Customer Business Report</div>
          </div>
          
          <div class="customer-info">
            <h2>Customer Information</h2>
            <p><strong>Name:</strong> ${customer.name}</p>
            <p><strong>Mobile:</strong> ${customer.mobile}</p>
            ${customer.shop_name ? `<p><strong>Shop:</strong> ${customer.shop_name}</p>` : ''}
            ${customer.location ? `<p><strong>Location:</strong> ${customer.location}</p>` : ''}
            <p><strong>Customer Code:</strong> ${customer.qr_code}</p>
            <p><strong>Report Generated:</strong> ${new Date().toLocaleDateString()}</p>
          </div>
          
          <div class="analytics-grid">
            <div class="analytics-card">
              <h3>Monthly Business</h3>
              <div class="value">₹${analytics.monthlyTotal.toFixed(2)}</div>
            </div>
            <div class="analytics-card">
              <h3>Yearly Business</h3>
              <div class="value">₹${analytics.yearlyTotal.toFixed(2)}</div>
            </div>
            <div class="analytics-card">
              <h3>Total Orders</h3>
              <div class="value">${analytics.totalOrders}</div>
            </div>
          </div>
          
          <div class="balance-status ${analytics.totalBalance === 0 ? 'balance-zero' : analytics.totalBalance > 0 ? 'balance-positive' : 'balance-negative'}">
            ${analytics.totalBalance === 0 
              ? 'No Outstanding Balance' 
              : analytics.totalBalance > 0 
                ? `Outstanding Amount: ₹${analytics.totalBalance.toFixed(2)}` 
                : `Advance Amount: ₹${Math.abs(analytics.totalBalance).toFixed(2)}`
            }
          </div>
          
          <div style="margin-top: 40px; font-size: 12px; color: #666; text-align: center;">
            Generated by GO GREEN LEAFY VEGETABLES Management System
          </div>
        </body>
      </html>
    `;
    
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  return (
    <Dialog open={true} onOpenChange={onClose}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Generate PDF Report</DialogTitle>
        </DialogHeader>
        
        <div className="space-y-4">
          <p>Generate a detailed business report for {customer.name} including:</p>
          <ul className="list-disc list-inside text-sm space-y-1">
            <li>Customer information</li>
            <li>Monthly and yearly business totals</li>
            <li>Outstanding balance details</li>
            <li>Order summary</li>
          </ul>
          
          <div className="flex gap-2">
            <Button onClick={generatePDF}>
              Generate & Print PDF
            </Button>
            <Button variant="outline" onClick={onClose}>
              Cancel
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default CustomerPDFReport;
