// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jecevdnuzbbznacpauct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplY2V2ZG51emJiem5hY3BhdWN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MDU3MjMsImV4cCI6MjA2NTE4MTcyM30.chXEke40EKW1dxD-9ZCOXEGoYBXOvmBYTfs2x07ZoH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);